# Generated by Django 5.1.7 on 2025-03-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_alter_list_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='collection',
            new_name='list',
        ),
    ]
