# Generated by Django 5.1.7 on 2025-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_rename_collection_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
