# Generated by Django 5.1.7 on 2025-06-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_list_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
